version: '3'

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: teste-creathus
      POSTGRES_USER: default
      POSTGRES_PASSWORD: secret
  app:
    build: .
    ports:
      - "9000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/teste-creathus
      SPRING_DATASOURCE_USERNAME: default
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - db